"""empty message

Revision ID: eb5d43531ef3
Revises: c3cceba30642
Create Date: 2023-01-16 03:04:44.321736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5d43531ef3'
down_revision = 'c3cceba30642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('past_shows_count')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('upcoming_shows_count')
        batch_op.drop_column('past_shows_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
